# -*- coding: utf-8 -*-
"""Model4_E-Commerce_Walmart_Dev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j_MM77CZ8fd5qpQkRhSOW8M43k3My1Ux
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('data.csv')
df.head()

# prompt: Using dataframe df: df.info()

# Display concise information about the dataframe
df.info()
df.describe()

df.isnull().sum()

df['email_open_rate'].head()

df['avg_order_value'].head()

df.shape

df['avg_order_value'].fillna(df['avg_order_value'].mean(), inplace=True)
df['email_open_rate'].fillna(df['email_open_rate'].mean(), inplace=True)

df['gender'].value_counts()
df['country'].value_counts()
df['preferred_category'].value_counts()

sns.countplot(x='gender', data=df, palette='Set2')
plt.title('Gender Distribution')
plt.show()

sns.histplot(df['age'], kde=True)
plt.title('Age Distribution of Customers')
plt.show()

# prompt: sns.countplot

import matplotlib.pyplot as plt
sns.countplot(x='is_fraudulent', data=df, palette='Set1')
plt.title('Fraudulent vs. Non-Fraudulent Customers')
plt.xticks([0, 1], ['Non-Fraudulent', 'Fraudulent'])
plt.show()

sns.histplot(df['loyalty_score'], bins=30, color=('yellow'), kde=True)
plt.xlabel('Loyalty Score')
plt.title('Loyalty Score Distribution')
plt.show()

sns.histplot(df['churn_risk'], bins=30, color=('purple'), kde=True)
plt.xlabel('Churn Risk')
plt.title('Churn Risk Distribution')
plt.show()

top_countries = df['country'].value_counts().head(10)
plt.figure(figsize=(10, 6))
sns.barplot(x=top_countries.index, y=top_countries.values, palette='viridis')
plt.title('Top 10 Countries with the Most Customers')
plt.xlabel('Country')
plt.ylabel('Number of Customers')
plt.xticks(rotation=45)
plt.show()

sns.scatterplot(x='avg_order_value', y='loyalty_score', hue='is_fraudulent', data=df)
plt.title('Average Order Value vs. Loyalty Score')
plt.xlabel('Average Order Value')
plt.ylabel('Loyalty Score')
plt.show()

sns.boxplot(x='gender', y='email_open_rate', data=df, palette='coolwarm')
plt.title('Email Open Rate by Gender')
plt.xlabel('Gender')
plt.ylabel('Email Open Rate')
plt.show()

plt.figure(figsize=(12, 6))
corr = df[['age', 'avg_order_value', 'total_orders', 'last_purchase', 'loyalty_score', 'churn_risk']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Heatmap')
plt.show()

sns.scatterplot(x='loyalty_score', y='churn_risk', hue='is_fraudulent', data=df)
plt.title('loyalty_score vs. Churn Risk')
plt.xlabel('Loyalty Score')
plt.ylabel('Churn Risk')
plt.show()

top_categories = df['preferred_category'].value_counts().head(10)
sns.barplot(x=top_categories.index, y=top_categories.values, palette='viridis')
plt.title('Top 10 Preferred Categories')
plt.xlabel('Category')
plt.ylabel('Number of Customers')

sns.histplot(df['total_orders'], bins=30, color=('green'), kde=True)
plt.xlabel('Total Orders')
plt.title('Total Orders Distribution')
plt.show()

df['customer_since'] = pd.to_datetime(df['customer_since'])
df['years_with_company'] = (datetime.now() - df['customer_since']).dt.days // 365
sns.histplot(df['years_with_company'], bins=30, color=('red'), kde=True)
plt.xlabel('Years with Company')
plt.title('Years with Company Distribution')
plt.show()

top_countries = df['country'].value_counts().nlargest(5).index

sns.boxplot(x='country', y='avg_order_value', data=df[df['country'].isin(top_countries)])
plt.title('Average Order Value by Country')
plt.xlabel('Country')
plt.ylabel('Average Order Value')

plt.show()

fraud_rate = df.groupby('country')['is_fraudulent'].mean().sort_values(ascending=False).head(10)
fraud_rate.plot(kind='bar', figsize=(10, 6))
plt.title('Top 10 Countries with the Highest Fraudulent Rate')
plt.xlabel('Country')
plt.ylabel('Fraudulent Rate')
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
le = LabelEncoder()
cat_cols = ['gender', 'country', 'preferred_category']
df_encoded = pd.get_dummies(df, columns=cat_cols, drop_first=True)

X = df_encoded.drop(['is_fraudulent', 'customer_id'], axis=1)
y = df_encoded['is_fraudulent']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
def evaluate_model(model, model_name):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{model_name} Accuracy: {accuracy:.2f}")
    print(classification_report(y_test, y_pred))

from sklearn.ensemble import RandomForestClassifier
evaluate_model(RandomForestClassifier(), "Random Forest")

from xgboost import XGBClassifier

evaluate_model(XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3), "XGBoost with Hyperparameters")

from sklearn.cluster import KMeans, DBSCAN, AgglomerativeClustering
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

clust_features = ['avg_order_value', 'loyalty_score', 'churn_risk', 'email_open_rate', 'total_orders']
X = df[clust_features]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=3, random_state=42)
df['cluster'] = kmeans.fit_predict(X_scaled)
plt.scatter(df['avg_order_value'], df['loyalty_score'], c=df['cluster'], cmap='viridis')
plt.xlabel('Average Order Value')
plt.ylabel('Loyalty Score')
plt.title('Customer Segmentation using K-Means Clustering')
plt.show()

from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

kmeans = KMeans(n_clusters=3, random_state=42)
df['kmeans_cluster'] = kmeans.fit_predict(X_scaled)

plt.scatter(X_pca[:, 0], X_pca[:, 1], c=df['kmeans_cluster'], cmap='Set1')
plt.title("KMeans Clustering (3 clusters)")
plt.show()


_______________________________________________________


Refactored Code -

1. Import Required Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import warnings

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

warnings.filterwarnings('ignore')

2. Data Loading and Initial Inspection

def load_data(filepath):
    df = pd.read_csv(filepath)
    return df

def display_basic_info(df):
    print("DataFrame Info:")
    df.info()
    print("\nDataFrame Description:")
    print(df.describe())
    print("\nMissing values:")
    print(df.isnull().sum())


    
3. Preprocessing and Missing Value Handling

def fill_missing_values(df):
    df['avg_order_value'].fillna(df['avg_order_value'].mean(), inplace=True)
    df['email_open_rate'].fillna(df['email_open_rate'].mean(), inplace=True)
    return df


4. Data Visualization
def plot_distributions(df):
    sns.countplot(x='gender', data=df, palette='Set2')
    plt.title('Gender Distribution')
    plt.show()

    sns.histplot(df['age'], kde=True)
    plt.title('Age Distribution')
    plt.show()

    sns.countplot(x='is_fraudulent', data=df, palette='Set1')
    plt.title('Fraudulent vs. Non-Fraudulent Customers')
    plt.xticks([0, 1], ['Non-Fraudulent', 'Fraudulent'])
    plt.show()

    sns.histplot(df['loyalty_score'], bins=30, color='yellow', kde=True)
    plt.xlabel('Loyalty Score')
    plt.title('Loyalty Score Distribution')
    plt.show()

    sns.histplot(df['churn_risk'], bins=30, color='purple', kde=True)
    plt.xlabel('Churn Risk')
    plt.title('Churn Risk Distribution')
    plt.show()

    top_countries = df['country'].value_counts().head(10)
    plt.figure(figsize=(10, 6))
    sns.barplot(x=top_countries.index, y=top_countries.values, palette='viridis')
    plt.title('Top 10 Countries with the Most Customers')
    plt.xlabel('Country')
    plt.ylabel('Number of Customers')
    plt.xticks(rotation=45)
    plt.show()

    sns.scatterplot(x='avg_order_value', y='loyalty_score', hue='is_fraudulent', data=df)
    plt.title('Average Order Value vs. Loyalty Score')
    plt.xlabel('Average Order Value')
    plt.ylabel('Loyalty Score')
    plt.show()

    sns.boxplot(x='gender', y='email_open_rate', data=df, palette='coolwarm')
    plt.title('Email Open Rate by Gender')
    plt.xlabel('Gender')
    plt.ylabel('Email Open Rate')
    plt.show()

    plt.figure(figsize=(12, 6))
    corr = df[['age', 'avg_order_value', 'total_orders', 'last_purchase', 'loyalty_score', 'churn_risk']].corr()
    sns.heatmap(corr, annot=True, cmap='coolwarm', linewidths=0.5)
    plt.title('Correlation Heatmap')
    plt.show()

    sns.scatterplot(x='loyalty_score', y='churn_risk', hue='is_fraudulent', data=df)
    plt.title('Loyalty Score vs. Churn Risk')
    plt.xlabel('Loyalty Score')
    plt.ylabel('Churn Risk')
    plt.show()

    top_categories = df['preferred_category'].value_counts().head(10)
    sns.barplot(x=top_categories.index, y=top_categories.values, palette='viridis')
    plt.title('Top 10 Preferred Categories')
    plt.xlabel('Category')
    plt.ylabel('Number of Customers')
    plt.show()

    sns.histplot(df['total_orders'], bins=30, color='green', kde=True)
    plt.xlabel('Total Orders')
    plt.title('Total Orders Distribution')
    plt.show()

    df['customer_since'] = pd.to_datetime(df['customer_since'])
    df['years_with_company'] = (datetime.now() - df['customer_since']).dt.days // 365
    sns.histplot(df['years_with_company'], bins=30, color='red', kde=True)
    plt.xlabel('Years with Company')
    plt.title('Years with Company Distribution')
    plt.show()

    top5_countries = df['country'].value_counts().nlargest(5).index
    sns.boxplot(x='country', y='avg_order_value', data=df[df['country'].isin(top5_countries)])
    plt.title('Average Order Value by Country')
    plt.xlabel('Country')
    plt.ylabel('Average Order Value')
    plt.show()

    fraud_rate = df.groupby('country')['is_fraudulent'].mean().sort_values(ascending=False).head(10)
    fraud_rate.plot(kind='bar', figsize=(10, 6))
    plt.title('Top 10 Countries with the Highest Fraudulent Rate')
    plt.xlabel('Country')
    plt.ylabel('Fraudulent Rate')
    plt.show()


5. Feature Encoding & Model Evaluation

def preprocess_data(df):
    cat_cols = ['gender', 'country', 'preferred_category']
    df_encoded = pd.get_dummies(df, columns=cat_cols, drop_first=True)
    X = df_encoded.drop(['is_fraudulent', 'customer_id'], axis=1)
    y = df_encoded['is_fraudulent']
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    return train_test_split(X_scaled, y, test_size=0.2, random_state=42)

def evaluate_model(model, X_train, X_test, y_train, y_test, model_name):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    print(f"{model_name} Accuracy: {accuracy:.2f}")
    print(classification_report(y_test, y_pred))


6. Clustering & Segmentation


def apply_clustering(df):
    clust_features = ['avg_order_value', 'loyalty_score', 'churn_risk', 'email_open_rate', 'total_orders']
    X = df[clust_features]
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    kmeans = KMeans(n_clusters=3, random_state=42)
    df['cluster'] = kmeans.fit_predict(X_scaled)

    plt.scatter(df['avg_order_value'], df['loyalty_score'], c=df['cluster'], cmap='viridis')
    plt.xlabel('Average Order Value')
    plt.ylabel('Loyalty Score')
    plt.title('Customer Segmentation using K-Means Clustering')
    plt.show()

    pca = PCA(n_components=2)
    X_pca = pca.fit_transform(X_scaled)
    df['kmeans_cluster'] = kmeans.fit_predict(X_scaled)

    plt.scatter(X_pca[:, 0], X_pca[:, 1], c=df['kmeans_cluster'], cmap='Set1')
    plt.title("KMeans Clustering (3 clusters)")
    plt.show()


7. Example Workflow


df = load_data('data.csv')
display_basic_info(df)
df = fill_missing_values(df)
plot_distributions(df)
X_train, X_test, y_train, y_test = preprocess_data(df)
evaluate_model(RandomForestClassifier(), X_train, X_test, y_train, y_test, "Random Forest")
apply_clustering(df)


